#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'singlelement' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def singlelement(n, arr):
    x=0
    for i in range(n):
        x=x^arr[i]
    return x

    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = singlelement(n, arr)

    fptr.write(str(result) + '\n')

    fptr.close()
